### PR TITLE
Add ghc 7 10 support

### PR DESCRIPTION
**Pull request by juanpaucar**
@sestrella @jsantos17 do you have any comments?

### CODE REVIEW

**Comment by sestrella** [comment]
@juanpaucar LGTM

**Comment by jsantos17** [comment]
LGTM. Merge after Travis passes.

**Comment by juanpaucar** [comment]
@jsantos17 @sestrella previosuly, in the travis file there was no cabal test, and tests seem to be failing in older compatible version, shoild i keep the cabal tests?

**Comment by juanpaucar** [comment]
@jsl @jsantos17 @sestrella any comments?

**Comment by sestrella** [comment]
@juanpaucar great job! LGTM

**Pull request merged**
