### PR TITLE
Handle command line options with GetOpt

### PR DESCRIPTION
**Pull request by jpvillaisaza**
See #33.

### CODE REVIEW

**Comment by jpvillaisaza** [comment]
@jsl @juanpaucar Can you take a look? This adds handling of command line options with System.Console.GetOpt (I used hapistrano as a test case for a blog post that I'm working on right now) and handles the case in which an environment variable is missing (instead of throwing an exception).

**Comment by juanpaucar** [comment]
I'm not sure about the use of `fromJust` I know that we are never going to hit an error because of [these lines](https://github.com/stackbuilders/hapistrano/pull/34/files#diff-63e7d2cbf23880a9c902c91fa34f6043R50) and using other ways of dealing with the `Nothing` would be unnecessary but it kinda looks weird.

But the overall LGTM

**Comment by jpvillaisaza** [comment]
@juanpaucar The use of `fromJust` was safe there, but not necessary. I force-pushed some changes to use `maybe` instead. It's prettier and simpler now.

**Comment by juanpaucar** [comment]
Indeed LGTM :shipit:

**Comment by jsl** [comment]
I just noticed this PR - sorry for the delay. @jpvillaisaza I'm fine with merging this unless you see a reason not to.

**Comment by jpvillaisaza** [comment]
@jsl Done. Thanks!

**Pull request merged**
