### PR TITLE
Fix Git configuration for tests

### PR DESCRIPTION
**Pull request by jpvillaisaza**
See #31.

### CODE REVIEW

**Comment by jpvillaisaza** [comment]
@juanpaucar Can you take a look? Do you think this change makes sense?

**Comment by juanpaucar** [comment]
Was the missing git configuration what made the tests fail in the stackage travis environment?

**Comment by jpvillaisaza** [comment]
@juanpaucar Yes, the Git configuration for push.default, user.email, and user.name was in our .travis.yml, so it worked only here.

**Comment by juanpaucar** [comment]
LGTM :shipit:

**Pull request merged**
